### PR TITLE
LCD sleep (and everyone's changes until now)

### PR DESCRIPTION
**Pull request by johntron**
This reverts 706d2bb19e41cac64bf5a576141aab1a80a06522 and e01963a7d0431d51a61ce7beec5770a7d8ccc216 replacing them with code that simply turns the LCD off after 8 seconds – from any menu. With this, I am able to print wirelessly via Octoprint without having to run to the printer to push the button.

The change returns to whichever menu the user was on upon awakening.

This PR also includes @Ryan-Hobbies, @crkochan, and mildmojo's changes.

### CODE REVIEW

**Comment by mildmojo** [comment]
Why do you prefer turning the LCD off over leaving it sitting at a menu?

**Comment by johntron** [comment]
@mildmojo to cover the case where we just rebooted the device and start a print remotely - this way we won't have to worry about pushing the button to go to a menu.

**Comment by mildmojo** [comment]
Oh. What about skipping the status screen on startup and going straight to the main menu? Smaller change with the same effect and won't time out in non-printing situations when you're using the status screen to measure heat-up or cooldown, like when you're doing a cold pull to clean the nozzle.

``` diff
# ultralcd.cpp
-menuFunc_t currentMenu = lcd_status_screen; /* function pointer to the currently active menu */
+menuFunc_t currentMenu = lcd_main_menu; /* function pointer to the currently active menu */
```

I've been thinking about using the main menu at boot anyway since I never control the printer remotely and I always need the menu before the status screen.

**Comment by johntron** [comment]
@mildmojo ah, ok. Both workflows could be supported with your proposal - I'll revise this PR sometime this week if nobody else has.

**Comment by mildmojo** [comment]
Cool. :dancer:

**Comment by mildmojo** [comment]
Hey @johntron, did you ever make that revision to skip straight to the main menu at boot?

**Pull request closed without merging**
