### PR TITLE
mildmojo's LCD update fix

### PR DESCRIPTION
**Pull request by Ryan-Hobbies**
The "ultralcd.cpp" change is mildmojo's fix for the head stuttering issue that is caused by the updating of the LCD on the info screen.  The LCD updates cause blobs on the print.  At least a couple of us have already been using this modified firmware with good success.

The Configuration.h file change is my extruder calibration change.  I'm not sure that everyone will have the same results, but my extruder calibration was of by almost 15%.  It seems to work good for me.

### CODE REVIEW

**Comment by jangrewe** [comment]
I'll do a quick test regarding the calibration when i get home, thanks for submitting this!

**Comment by mildmojo** [comment]
I'm not sure the LCD timeout fix will work. I think that was the first method I tried, which caused the menu to go into a tight redraw loop, slowing the whole printer down. To verify, start a print and stare at the single heartbeat pixel location at the bottom right of the LCD. Make sure it doesn't toggle after 15s, 20s, 30s.

Is the extruder calibration universal, or is that a per-printer thing? I've been using the stock setting so far and it seems okay.

**Comment by Ryan-Hobbies** [comment]
You are correct, mildmojo.  I made a mistake on that first pull request.  I've actually made both of your suggested modifications to the ultralcd.cpp file.  I forgot to include the other piece, which is even more important.  I'll fix that now.  Thanks again, for your effort.

The extruder calibration is not exactly universal, but it should be pretty close for everyone that has the same machine.  It can be slightly impacted by different material types and such.  I was surprised that it was off by so much.  My prints seem to be filled in a little better since I made the change.

**Comment by mildmojo** [comment]
:+1:

Side note, your comment says both modifications are necessary, but really only the second bit you've added is necessary to keep it from timing out back to the status screen. Redefining the screen that the "return to status" function goes to is handy, but not required. No big deal.

**Comment by mildmojo** [comment]
Did you mean to merge the changes from #2 into this pull request?

**Comment by Ryan-Hobbies** [comment]
No, I didn't.  I'm new to Github contributions.  How do I make another modification to my fork without merging this?  Should I have created another fork from mine?  I'm just trying to keep track of the changes that I've made.

**Comment by mildmojo** [comment]
It looks like you opened the pull request from your master to this repo's master. Usually you'll create a branch on your fork that contains the changes, then make a pull request from that branch to this repo's master.

To keep the branch (and pull request) containing just your changes from this repo's master, make the branch point the same commit as this repo's head on master. This repo's head is at aef658 right now, so you could `git branch my_mods aef658 && git checkout my_mods`, then start making changes and eventually open a PR from `my_mods`.

With a fork, I think you usually leave your copy of master synchronized with the upstream repo and do all your work in branches. If the upstream master changes while you're working on a branch, you'll want to pull the changes to your fork's master, then rebase your branch to the new head.

If you want to integrate two branches on your repo for testing, you can create a new branch from master and merge the two branches into it.

**Comment by Ryan-Hobbies** [comment]
Thanks for the info.  You are correct.  Rookie mistake.  I'll see if I can get it fixed later.  I think that I'm going to have to remove this original pull request, add the branches on my fork, and re-issue the pull request.  It's all a little foreign to me, but this is a good learning opportunity on this small project.  :)

**Comment by mildmojo** [comment]
Awesome! :facepunch:

**Comment by Ryan-Hobbies** [comment]
I'm removing this original pull request for now... I accidentally added some other modifications to this same pull request.  I'll reissue the pull request after I clean things up.  Rookie mistake on Github!

**Pull request closed without merging**
